debug: false
# ????? ????? ?? ??? ?? ?? ?? ???(?? ???? ?? ?? ?? ? ? ??)
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.board.fastcampusboard: debug
    org.springframework.web.servlet: debug  #? ??? ??? ??? ?? ????, ???? ??? ?? ???? ??? ? ? ??.
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA ??? ?? ? ? Query ?? ???? ?? ???? ??.

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/fboard
    username: root
    password: cos1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # springboot 2.4 ???? ?? / ???? ?????? ???? ?? ? ?? ?
    hibernate:
      ddl-auto: create # ??? ??  ??
    show-sql: true # sql ?? ???
    properties:
      hibernate:
        format_sql: true # ??? ??? ???? ?? ?? ??
        default_batch_fetch_size: 100 # ?? ?? join ?? ??? ??? ??? select ?? (10? -> 1?) ??
  h2:
    console:
      enabled: false #
  sql:
    init:
      mode: never  # resources ? ??? data.sql ? ?? ?? ??? (??? ?? ??? ??? db ??)

---

spring:
  config:
    activate:
      on-profile: testdb # ??? DB profile ? activate(???) ??? ? ? ??? ???
#  datasource:
#    url: jdbc:h2:mem:board;mode=mariadb
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none


